name: pipeline

on: 
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout source code
        uses: actions/checkout@v3

      - name: Set up Python 3.8.13
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.13

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: false
          virtualenvs-path: ~/.virtualenvs

      - name: Install Dependencies
        run: poetry install

      - name: default deploy
        uses: Alphacode18/Dilbert@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: Dilbert
          source: .
