name: run-integration

on:
  pull_request:
     branches:
       - "master"

jobs:
  run-integration:
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: ["dilbert"] }
    defaults:
      run:
        working-directory: ${{ matrix.dir }}
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.13
      - name: install poetry
        uses: snok/install-poetry@v1
      - name: install library
        run: poetry install
      - name: lint source code
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "."
      - name: run tests
        run: |
          poetry run python -m pytest
